// Development-only ANM viewer linked to the existing shared SDL3 renderer.
import{spawn}from'node:child_process';import{readFileSync,writeFileSync,readdirSync,mkdirSync,existsSync,copyFileSync}from'node:fs';import{resolve,relative}from'node:path';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';
const root=fileURLToPath(new URL('../',import.meta.url)),workspace=resolve(root,'..'),sdk=resolve(workspace,'tools/emsdk'),out=resolve(root,'artifacts/anm-viewer'),objects=resolve(out,'objects');mkdirSync(objects,{recursive:true});
const env={...process.env,EM_CONFIG:resolve(sdk,'.emscripten'),EMSDK:sdk,EMCC_CORES:'4'},flags=['-O2','-g0','-std=c++17','-ffp-contract=off','-fno-strict-aliasing','-fno-exceptions','-fno-rtti','-DTH_NATIVE_PLATFORM=1','--use-port=sdl3'];
const run=args=>new Promise((accept,reject)=>{const p=spawn('python',[resolve(sdk,'install/emscripten/emcc.py'),...args],{cwd:root,env,windowsHide:true,stdio:['ignore','pipe','pipe']});let log='';for(const s of[p.stdout,p.stderr])s.on('data',b=>{log+=b;process.stdout.write(b);});p.on('error',reject);p.on('exit',n=>n?reject(Error('Viewer build failed '+n+'\n'+log)):accept());});
const source=['cpp/game','cpp/sdl'].flatMap(dir=>readdirSync(resolve(root,dir)).filter(n=>n.endsWith('.cpp')).sort().map(n=>resolve(root,dir,n)));source.push(resolve(root,'tests/browser/anm-viewer.cpp'));
const walk=dir=>readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(resolve(dir,e.name)):/\.(h|hpp|inc)$/.test(e.name)?[resolve(dir,e.name)]:[]),headers=[...walk(resolve(root,'cpp')),...walk(resolve(workspace,'portable/sdl'))];
const sha=b=>createHash('sha256').update(b).digest('hex'),settings=JSON.stringify([flags,headers.map(n=>[n,sha(readFileSync(n))])]);
async function compile(path){const obj=resolve(objects,relative(workspace,path).replaceAll('\\','_').replaceAll('/','_')+'.o'),key=sha(settings+sha(readFileSync(path)));if(!existsSync(obj)||!existsSync(obj+'.key')||readFileSync(obj+'.key','utf8')!==key){await run([...flags,'-c',path,'-o',obj]);writeFileSync(obj+'.key',key);}return obj;}
const sharedPath=resolve(workspace,'portable/sdl/Renderer.cpp'),shared=await compile(sharedPath),compiled=new Array(source.length);let cursor=0;
await Promise.all(Array.from({length:4},async()=>{while(cursor<source.length){const i=cursor++;compiled[i]=await compile(source[i]);}}));
const loader=resolve(out,'viewer.mjs');await run([...flags,'--no-entry','-sDEFAULT_TO_CXX=1','-sMODULARIZE=1','-sEXPORT_ES6=1','-sENVIRONMENT=web','-sALLOW_MEMORY_GROWTH=1','-sSTACK_SIZE=1048576','-sINITIAL_MEMORY=67108864','-sMAXIMUM_MEMORY=536870912','-sFILESYSTEM=0','-sEXPORTED_RUNTIME_METHODS=HEAPU8,HEAPU32,UTF8ToString','-sINVOKE_RUN=0','-sEXIT_RUNTIME=0','-sMIN_WEBGL_VERSION=2','-sMAX_WEBGL_VERSION=2','-sGL_SUPPORT_AUTOMATIC_ENABLE_EXTENSIONS=0',...compiled,shared,'-o',loader]);
const wasm=readFileSync(resolve(out,'viewer.wasm'));writeFileSync(resolve(out,'build.json'),JSON.stringify({kind:'th11-development-anm-viewer',completeGame:false,sha256:sha(wasm),bytes:wasm.length,sources:Object.fromEntries([...source,sharedPath,...headers].map(p=>[relative(workspace,p).replaceAll('\\','/'),sha(readFileSync(p))])),imports:WebAssembly.Module.imports(new WebAssembly.Module(wasm))},null,2));
for(const name of ['index.html','viewer.js'])copyFileSync(resolve(root,'tests/browser',name),resolve(out,name));console.log(JSON.stringify({loader,bytes:wasm.length,completeGame:false}));
