import createViewer from './viewer.mjs';
const status=document.querySelector('#status'),asset=document.querySelector('#asset'),script=document.querySelector('#script'),load=document.querySelector('#load'),pause=document.querySelector('#pause'),step=document.querySelector('#step');
let module,playing=false,loaded=false,previous=0,accumulator=0,loading=false;
const params=new URLSearchParams(location.search),fail=e=>{playing=false;status.textContent='失败：'+(e?.message||e);document.body.dataset.state='error';};
function show(){status.textContent=JSON.stringify({asset:asset.value,script:+script.value,frame:module._th11_viewer_frames(),active:module._th11_viewer_active(),playing,backend:'shared SDL3 / WebGL2',completeGame:false},null,2);}
function tick(){if(!module._th11_viewer_step())throw Error(module.UTF8ToString(module._th11_viewer_error()));}
async function open(){if(loading)return;loading=true;playing=false;loaded=false;try{const response=await fetch('/assets/'+encodeURIComponent(asset.value));if(!response.ok)throw Error('资源读取失败 '+response.status);const bytes=new Uint8Array(await response.arrayBuffer()),p=module._th11_viewer_allocate(bytes.length);if(!p)throw Error('资源内存不足');try{module.HEAPU8.set(bytes,p);if(!module._th11_viewer_open(p,bytes.length,+script.value))throw Error(module.UTF8ToString(module._th11_viewer_error()));}finally{module._th11_viewer_release(p);}tick();loaded=true;playing=params.get('paused')!=='1';previous=0;accumulator=0;document.body.dataset.state='ready';pause.textContent=playing?'暂停':'播放';show();}catch(e){fail(e);}finally{loading=false;}}
load.onclick=open;pause.onclick=()=>{if(!loaded)return;playing=!playing;previous=0;accumulator=0;pause.textContent=playing?'暂停':'播放';show();};step.onclick=()=>{if(!loaded)return;playing=false;pause.textContent='播放';try{tick();show();}catch(e){fail(e);}};
try{const names=await(await fetch('/assets.json')).json();for(const name of names)asset.add(new Option(name,name));asset.value=names.includes(params.get('asset'))?params.get('asset'):names.includes('title.anm')?'title.anm':names[0];script.value=params.get('script')||'0';module=await createViewer({canvas:document.querySelector('#canvas'),printErr:console.error});if(!module._th11_viewer_initialize())throw Error(module.UTF8ToString(module._th11_viewer_error()));load.disabled=pause.disabled=step.disabled=false;await open();requestAnimationFrame(function frame(t){try{if(playing&&loaded){if(previous)accumulator+=Math.min(100,t-previous);previous=t;while(accumulator>=1000/60){tick();accumulator-=1000/60;}if(module._th11_viewer_frames()%30===0)show();}}catch(e){fail(e);}requestAnimationFrame(frame);});}catch(e){fail(e);}
